CREATE TABLE IF NOT EXISTS PURCHASE_HISTORY (
	ID SERIAL PRIMARY KEY,
	CUSTOMER_ID VARCHAR(255) NOT NULL,
	PURCHASE_DATE DATE NOT NULL,
	ITEM_NAME VARCHAR(255) NOT NULL,
	AMOUNT INTEGER NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS USER_MONTHLY_POINTS (
	CUSTOMER_ID VARCHAR(255) NOT NULL,
	YEAR_MONTH VARCHAR(7) NOT NULL,
	TOTAL_POINTS INTEGER NOT NULL,
	PRIMARY KEY (CUSTOMER_ID, YEAR_MONTH)
);