CREATE TABLE IF NOT EXISTS T_SCORE (
    SCORE_ID SERIAL PRIMARY KEY,
    USER_ID VARCHAR(16) NOT NULL,
    ANS_NUM_CORRECT INTEGER,
    ANS_NUM_WRONG INTEGER,
    TIME DECIMAL(6,3) NOT NULL,
    SCORE INTEGER,
    USER_RANK CHAR(1) NOT NULL,
    INSERT_USER_ID VARCHAR(16) NOT NULL,
    INSERT_DATE TIMESTAMP NOT NULL,
    UPDATE_USER_ID VARCHAR(16) NOT NULL,
    UPDATE_DATE TIMESTAMP NOT NULL,
    DELETE_FLG CHAR(1) NOT NULL DEFAULT '0',
    UPDATE_COUNT INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS T_GAME_HISTORY (
    HISTORY_ID SERIAL PRIMARY KEY,
    TOTAL_PLAY_NUMBERS INTEGER NOT NULL,
    TODAY_PLAY_NUMBERS INTEGER NOT NULL,
    INSERT_USER_ID VARCHAR(16) NOT NULL,
    INSERT_DATE TIMESTAMP NOT NULL,
    UPDATE_USER_ID VARCHAR(16) NOT NULL,
    UPDATE_DATE TIMESTAMP NOT NULL,
    DELETE_FLG CHAR(1) NOT NULL DEFAULT '0',
    UPDATE_COUNT INTEGER NOT NULL
);